version: "3.8"

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    ports:
      - "7878:7878" # radarr
      - "8880:8880" # qbittorrent
      - "8989:8989" # sonarr
      - "9696:9696" # prowlarr
    environment:
      VPN_SERVICE_PROVIDER: protonvpn
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
      SERVER_COUNTRIES: Switzerland
      VPN_PORT_FORWARDING: on
      VPN_PORT_FORWARDING_PROVIDER: protonvpn
      EXTRA_SUBNETS: 192.168.0.0/16
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      start_period: 15s
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      WEBUI_PORT: 8880
      DOCKER_MODS: ghcr.io/t-anc/gsp-qbittorent-gluetun-sync-port-mod:main
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume2/docker/data/qbittorrent/config:/config
      - /volume1/data:/data
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: service:gluetun
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume2/docker/data/prowlarr/config:/config
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: service:gluetun
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume2/docker/data/sonarr/config:/config
      - /volume1/data:/data
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: service:gluetun
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume2/docker/data/radarr/config:/config
      - /volume1/data:/data
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped
